import { useEffect, useState } from "react";
import { ShoppingCart, ChevronLeft, ChevronRight, ExternalLink } from "lucide-react";
import { Link } from "react-router-dom";
import { useCartStore } from "../stores/useCartStore";
import { useUserStore } from "../stores/useUserStore";
import toast from "react-hot-toast";

const FeaturedProducts = ({ featuredProducts = [] }) => {
    const [currentIndex, setCurrentIndex] = useState(0); const [itemsPerPage, setItemsPerPage] = useState(4);
    const { addToCart } = useCartStore(); const { user } = useUserStore();
    useEffect(() => { const resize = () => setItemsPerPage(window.innerWidth < 640 ? 1 : window.innerWidth < 1024 ? 2 : window.innerWidth < 1280 ? 3 : 4); resize(); window.addEventListener("resize", resize); return () => window.removeEventListener("resize", resize); }, []);
    useEffect(() => { setCurrentIndex((i) => Math.min(i, Math.max(0, featuredProducts.length - itemsPerPage))); }, [featuredProducts.length, itemsPerPage]);
    const add = (product) => { if (!user) return toast.error("Please login to add products to cart"); if (Number(product.stock) <= 0) return toast.error("This product is out of stock"); addToCart(product); };
    if (!featuredProducts.length) return null;
    const maxIndex = Math.max(0, featuredProducts.length - itemsPerPage);
    return <section className="py-12" aria-labelledby="featured-heading"><div className="container mx-auto px-4"><div className="mb-6 flex items-end justify-between gap-4"><div><h2 id="featured-heading" className="text-4xl font-bold text-yellow-400">Featured</h2><p className="mt-1 text-stone-400">Hand-picked pieces worth a closer look.</p></div><Link to="/shop?sort=featured" className="text-sm text-yellow-400 hover:text-yellow-300">View all →</Link></div><div className="relative"><div className="overflow-hidden"><div className="flex transition-transform duration-300" style={{ transform: `translateX(-${currentIndex * (100 / itemsPerPage)}%)` }}>{featuredProducts.map((product) => <div key={product._id} className="w-full shrink-0 px-2 sm:w-1/2 lg:w-1/3 xl:w-1/4"><article className="h-full overflow-hidden rounded-lg border border-yellow-500/30 bg-white/10 shadow-lg"><Link to={`/product/${product._id}`}><img src={product.image} alt={product.name} className="h-48 w-full object-cover transition-transform duration-300 hover:scale-105" loading="lazy"/></Link><div className="p-4"><Link to={`/product/${product._id}`}><h3 className="font-semibold text-white hover:text-yellow-400">{product.name}</h3></Link><p className="mb-4 mt-2 font-medium text-yellow-300">${Number(product.price).toFixed(2)}</p><button onClick={() => add(product)} disabled={Number(product.stock) <= 0} className="w-full rounded bg-yellow-600 py-2 font-semibold disabled:bg-stone-700"><ShoppingCart className="mr-2 inline h-5 w-5"/>{Number(product.stock) <= 0 ? "Out of stock" : "Add to Cart"}</button><Link to={`/product/${product._id}`} className="mt-3 block text-center text-sm text-yellow-400"><ExternalLink className="mr-1 inline h-4 w-4"/>View details</Link></div></article></div>)}</div></div><button aria-label="Previous featured products" onClick={() => setCurrentIndex((i) => Math.max(0, i - itemsPerPage))} disabled={currentIndex === 0} className="absolute -left-3 top-1/2 -translate-y-1/2 rounded-full bg-yellow-600 p-2 disabled:cursor-not-allowed disabled:opacity-30"><ChevronLeft/></button><button aria-label="Next featured products" onClick={() => setCurrentIndex((i) => Math.min(maxIndex, i + itemsPerPage))} disabled={currentIndex >= maxIndex} className="absolute -right-3 top-1/2 -translate-y-1/2 rounded-full bg-yellow-600 p-2 disabled:cursor-not-allowed disabled:opacity-30"><ChevronRight/></button></div></div></section>;
};
export default FeaturedProducts;
