import { useState } from "react";
import { Facebook, Instagram, Twitter, ChevronUp, Store, Search } from "lucide-react";
import { Link } from "react-router-dom";
import axiosInstance from "../lib/axios";
import toast from "react-hot-toast";
const categories = [{ href: "/category/jeans", name: "Jeans" }, { href: "/category/t-shirts", name: "T-shirts" }, { href: "/category/shoes", name: "Shoes" }, { href: "/category/glasses", name: "Glasses" }, { href: "/category/jackets", name: "Jackets" }, { href: "/category/suits", name: "Suits" }, { href: "/category/bags", name: "Bags" }];
export default function Footer() {
  const [email, setEmail] = useState(""); const [loading, setLoading] = useState(false);
  const handleSubscribe = async (e) => { e.preventDefault(); setLoading(true); try { const { data } = await axiosInstance.post("/support/subscribe", { email }); toast.success(data.message); setEmail(""); } catch (error) { toast.error(error.response?.data?.message || "Unable to subscribe right now"); } finally { setLoading(false); } };
  return <footer className="bg-stone-900 pt-12 text-stone-300"><div className="mx-auto grid max-w-7xl grid-cols-1 gap-8 px-4 sm:grid-cols-2 lg:grid-cols-4 sm:px-6 lg:px-8"><div><h3 className="mb-4 text-lg font-bold text-yellow-400">About Us</h3><p className="text-sm leading-relaxed">We’re a men’s fashion brand dedicated to sustainability, quality, and timeless style. Look good. Feel better.</p></div><nav aria-label="Store and customer service"><h3 className="mb-4 text-lg font-bold text-yellow-400">Store & Help</h3><ul className="space-y-2 text-sm"><li><Link to="/shop" className="flex items-center gap-2 hover:text-yellow-400"><Store size={15}/> Shop All</Link></li><li><Link to="/search" className="flex items-center gap-2 hover:text-yellow-400"><Search size={15}/> Search</Link></li><li><Link to="/contact" className="hover:underline">Contact Us</Link></li><li><Link to="/faq" className="hover:underline">FAQ</Link></li><li><Link to="/shipping-returns" className="hover:underline">Shipping & Returns</Link></li><li><Link to="/support" className="hover:underline">Support</Link></li></ul></nav><nav aria-label="Categories"><h3 className="mb-4 text-lg font-bold text-yellow-400">Categories</h3><ul className="grid grid-cols-2 gap-2 text-sm">{categories.map((category) => <li key={category.name}><Link to={category.href} className="hover:text-yellow-400">{category.name}</Link></li>)}</ul></nav><div><h3 className="mb-4 text-lg font-bold text-yellow-400">Subscribe</h3><p className="mb-2 text-sm">Stay in the loop with new drops and exclusive offers.</p><form onSubmit={handleSubscribe} className="flex flex-col gap-2 sm:flex-row"><label htmlFor="footer-email" className="sr-only">Email address</label><input id="footer-email" type="email" value={email} onChange={(e) => setEmail(e.target.value)} placeholder="Your email" required maxLength={254} className="w-full rounded-md px-3 py-2 text-black"/><button type="submit" disabled={loading} className="rounded-md bg-yellow-400 px-4 py-2 font-semibold text-black disabled:opacity-50">{loading ? "Joining…" : "Subscribe"}</button></form></div></div><div className="mx-auto mt-10 flex max-w-7xl items-center justify-between border-t border-stone-700 px-4 pt-6 sm:px-6 lg:px-8"><div className="flex space-x-6"><a href="https://facebook.com" aria-label="Facebook" className="hover:text-white"><Facebook className="h-6 w-6"/></a><a href="https://instagram.com" aria-label="Instagram" className="hover:text-white"><Instagram className="h-6 w-6"/></a><a href="https://twitter.com" aria-label="Twitter" className="hover:text-white"><Twitter className="h-6 w-6"/></a></div><button onClick={() => window.scrollTo({ top: 0, behavior: "smooth" })} aria-label="Back to top" className="rounded-full p-2 hover:bg-stone-700"><ChevronUp className="h-6 w-6 text-stone-400"/></button></div><div className="pb-4 pt-6 text-center text-xs text-stone-500">&copy; {new Date().getFullYear()} Thread Theory. All rights reserved.</div></footer>;
}
