import { useEffect, useState } from "react";
import { ShoppingCart, UserPlus, LogIn, LogOut, Lock, ShoppingBag, UserRound, Package, Search, Bell, Menu, X, Store, HelpCircle } from "lucide-react";
import { Link, useNavigate } from "react-router-dom";
import { useUserStore } from "../stores/useUserStore";
import { useCartStore } from "../stores/useCartStore";
import { useNotificationStore } from "../stores/useNotificationStore";

const Navbar = () => {
    const { user, logout } = useUserStore(); const { cart } = useCartStore(); const { notifications, unread, fetchNotifications, markRead, markAllRead } = useNotificationStore();
    const isAdmin = user?.role === "admin"; const navigate = useNavigate();
    const [query, setQuery] = useState(""); const [open, setOpen] = useState(false); const [mobileOpen, setMobileOpen] = useState(false);
    useEffect(() => { if (user) fetchNotifications(); }, [user, fetchNotifications]);
    const submitSearch = (e) => { e.preventDefault(); const q = query.trim(); setMobileOpen(false); navigate(q ? `/search?q=${encodeURIComponent(q)}` : "/search"); };
    const closeMobile = () => setMobileOpen(false);
    return <header className="fixed top-0 left-0 w-full border-b border-yellow-800 bg-stone-900/95 shadow-lg backdrop-blur-md z-40"><div className="container mx-auto px-4 py-3"><div className="flex items-center justify-between gap-3">
        <Link to="/" onClick={closeMobile} className="flex items-center text-xl font-bold text-yellow-400 sm:text-2xl"><ShoppingBag className="mr-2" size={30}/>Thread Theory</Link>
        <form onSubmit={submitSearch} className="hidden flex-1 items-center rounded-md border border-stone-700 bg-stone-800 px-2 md:flex md:max-w-sm"><Search size={17} className="text-stone-400"/><label htmlFor="nav-search" className="sr-only">Search products</label><input id="nav-search" value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search products…" className="w-full bg-transparent px-2 py-2 text-sm outline-none"/><button className="px-2 py-1 text-xs font-semibold text-yellow-400">Search</button></form>
        <button aria-label={mobileOpen ? "Close navigation" : "Open navigation"} onClick={() => setMobileOpen((v) => !v)} className="rounded-md p-2 text-stone-200 hover:bg-stone-800 md:hidden">{mobileOpen ? <X/> : <Menu/>}</button>
        <nav className="hidden items-center gap-3 md:flex"><Link to="/" className="text-stone-300 hover:text-yellow-400">Home</Link><Link to="/shop" className="flex items-center gap-1 text-stone-300 hover:text-yellow-400"><Store size={18}/>Shop</Link><Link to="/search" className="flex items-center gap-1 text-stone-300 hover:text-yellow-400"><Search size={18}/>Search</Link>{user && <><Link to="/orders" className="flex items-center gap-1 text-stone-300 hover:text-yellow-400"><Package size={18}/><span>Orders</span></Link><Link to="/account" className="flex items-center gap-1 text-stone-300 hover:text-yellow-400"><UserRound size={18}/><span>Account</span></Link><div className="relative"><button onClick={() => setOpen((v) => !v)} aria-label="Notifications" className="relative p-1 text-stone-300 hover:text-yellow-400"><Bell size={20}/>{unread > 0 && <span className="absolute -right-1 -top-1 rounded-full bg-yellow-500 px-1.5 py-0.5 text-[10px] font-bold text-stone-900">{unread}</span>}</button>{open && <div className="absolute right-0 mt-2 w-80 max-w-[90vw] rounded-lg border border-stone-700 bg-stone-900 p-3 shadow-xl z-50"><div className="mb-2 flex items-center justify-between"><strong>Notifications</strong>{unread > 0 && <button onClick={markAllRead} className="text-xs text-yellow-400">Mark all read</button>}</div><div className="max-h-80 space-y-2 overflow-auto">{!notifications.length && <p className="p-3 text-sm text-stone-400">No notifications yet.</p>}{notifications.map((n) => <button key={n._id} onClick={() => markRead(n._id)} className={`block w-full rounded p-3 text-left ${n.read ? "bg-stone-800" : "bg-stone-700"}`}><div className="text-sm font-medium">{n.title}</div><div className="mt-1 text-xs text-stone-400">{n.message}</div></button>)}</div></div>}</div><Link to="/cart" className="relative text-stone-300 hover:text-yellow-400"><ShoppingCart className="mr-1 inline-block" size={20}/><span>Cart</span>{cart.length > 0 && <span className="absolute -left-2 -top-2 rounded-full bg-yellow-500 px-2 py-0.5 text-xs text-white">{cart.length}</span>}</Link></>}{isAdmin && <Link className="flex items-center rounded-md bg-yellow-700 px-3 py-1 font-medium text-white hover:bg-yellow-600" to="/secret-dashboard"><Lock className="mr-1" size={18}/>Dashboard</Link>}{user ? <button className="flex items-center rounded-md bg-stone-700 px-3 py-2 text-white hover:bg-stone-600" onClick={logout}><LogOut size={18}/><span className="ml-2">Log Out</span></button> : <><Link to="/signup" className="flex items-center rounded-md bg-yellow-600 px-3 py-2 text-white hover:bg-yellow-700"><UserPlus className="mr-2" size={18}/>Sign Up</Link><Link to="/login" className="flex items-center rounded-md bg-stone-700 px-3 py-2 text-white"><LogIn className="mr-2" size={18}/>Login</Link></>}</nav>
    </div>{mobileOpen && <div className="border-t border-stone-800 pb-3 pt-3 md:hidden"><form onSubmit={submitSearch} className="mb-3 flex items-center rounded-md border border-stone-700 bg-stone-800 px-2"><Search size={17} className="text-stone-400"/><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search products…" className="w-full bg-transparent px-2 py-3 outline-none"/><button className="text-xs font-semibold text-yellow-400">Search</button></form><div className="grid gap-1">{[["/","Home"],["/shop","Shop"],["/search","Search"], ...(user ? [["/orders","Orders"],["/account","Account"],["/cart","Cart"],["/support","Support"]] : [["/support","Support"],["/login","Login"],["/signup","Sign Up"]])].map(([href,label]) => <Link key={href} to={href} onClick={closeMobile} className="rounded-md px-3 py-3 text-stone-200 hover:bg-stone-800 hover:text-yellow-400">{label}</Link>)}{isAdmin && <Link to="/secret-dashboard" onClick={closeMobile} className="rounded-md px-3 py-3 text-yellow-400 hover:bg-stone-800">Dashboard</Link>}{user && <button onClick={() => { closeMobile(); logout(); }} className="rounded-md px-3 py-3 text-left text-stone-200 hover:bg-stone-800">Log Out</button>}</div></div>}</div></header>;
};
export default Navbar;
