import { useEffect } from "react";
import { useOrderStore } from "../stores/useOrderStore";

const stages = ["processing", "shipped", "delivered"];
const OrdersPage = () => {
    const { orders, loading, fetchMyOrders } = useOrderStore();
    useEffect(() => { fetchMyOrders(); }, [fetchMyOrders]);
    return <main className='container mx-auto min-h-screen px-4 py-16'><h1 className='mb-8 text-3xl font-bold'>My Orders</h1>{loading && !orders.length && <p className='text-stone-400'>Loading orders...</p>}{!loading && !orders.length && <p className='text-stone-400'>You have no orders yet.</p>}<div className='space-y-4'>{orders.map((order) => { const current = stages.indexOf(order.status); return <article key={order._id} className='rounded-lg border border-stone-700 bg-stone-800 p-5'><div className='mb-4 flex flex-wrap justify-between gap-3'><div><h2 className='font-semibold'>Order #{order._id.slice(-8)}</h2><p className='text-sm text-stone-400'>{new Date(order.createdAt).toLocaleDateString()}</p></div><span className={`rounded-full px-3 py-1 text-sm capitalize ${order.status === 'cancelled' || order.status === 'refunded' ? 'bg-red-900 text-red-200' : 'bg-stone-700'}`}>{order.status || 'processing'}</span></div>{!['cancelled','refunded'].includes(order.status) && <div className='mb-5 flex items-center'>{stages.map((stage,index)=><div key={stage} className='flex flex-1 items-center'>{<div className={`h-3 w-3 rounded-full ${index <= current ? 'bg-yellow-500' : 'bg-stone-600'}`}/>} {index < stages.length-1 && <div className={`h-1 flex-1 ${index < current ? 'bg-yellow-500' : 'bg-stone-600'}`}/>}</div>)}</div>}{order.trackingNumber && <p className='mb-4 text-sm text-stone-300'>Tracking: <strong>{order.carrier ? `${order.carrier} · ` : ''}{order.trackingNumber}</strong></p>}<div className='space-y-2'>{order.products?.map((item,index)=><div key={`${order._id}-${index}`} className='flex items-center justify-between gap-3 text-sm'><span className='flex items-center gap-2'>{item.product?.image && <img src={item.product.image} alt='' className='h-10 w-10 rounded object-cover'/>}{item.quantity} × {item.product?.name || 'Product'}</span><span>${(Number(item.price)*Number(item.quantity)).toFixed(2)}</span></div>)}</div><div className='mt-4 flex justify-between border-t border-stone-700 pt-4 font-semibold'><span>Total</span><span className='text-yellow-400'>${Number(order.totalAmount).toFixed(2)}</span></div>{order.shippingAddress && <p className='mt-3 text-sm text-stone-400'>Ship to: {order.shippingAddress.line1}, {order.shippingAddress.city}, {order.shippingAddress.state} {order.shippingAddress.postalCode}</p>}</article>;})}</div></main>;
};
export default OrdersPage;
