import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, Heart, ShoppingCart, Star } from "lucide-react";
import { Link, useNavigate, useParams } from "react-router-dom";
import toast from "react-hot-toast";
import axios from "../lib/axios";
import ProductCard from "../components/ProductCard";
import { useProductStore } from "../stores/useProductStore";
import { useCartStore } from "../stores/useCartStore";
import { useUserStore } from "../stores/useUserStore";

export default function ProductDetailPage() {
  const { id } = useParams(); const navigate = useNavigate();
  const { fetchProductById } = useProductStore(); const { addToCart } = useCartStore(); const { user } = useUserStore();
  const [product, setProduct] = useState(null); const [loading, setLoading] = useState(true); const [selectedVariant, setSelectedVariant] = useState(null); const [reviews, setReviews] = useState([]); const [average, setAverage] = useState(0); const [wishlisted, setWishlisted] = useState(false);
  useEffect(() => { (async () => { setLoading(true); const item = await fetchProductById(id); setProduct(item); setSelectedVariant(item?.variants?.[0] || null); setLoading(false); })(); }, [id, fetchProductById]);
  useEffect(() => { if (!id) return; axios.get(`/account/reviews/${id}`).then(({data}) => { setReviews(data.reviews || []); setAverage(data.average || 0); }).catch(() => {}); }, [id]);
  useEffect(() => { if (user && id) axios.get("/account/wishlist").then(({data}) => setWishlisted((data.products || []).some((item) => item._id === id))).catch(() => {}); }, [user, id]);
  const price = Number(selectedVariant?.price ?? product?.price ?? 0); const stock = Number(selectedVariant?.stock ?? product?.stock ?? 0); const outOfStock = stock <= 0;
  const recommendationParams = useMemo(() => product ? { category: product.category, sort: "featured" } : null, [product]);
  const add = async () => { if (!user) return toast.error("Please login to add products to cart"); if (outOfStock) return toast.error("This item is out of stock"); await addToCart({ ...product, price, variantId: selectedVariant?._id }); };
  const toggleWishlist = async () => { if (!user) return toast.error("Please login to use your wishlist"); try { const { data } = await axios.patch(`/account/wishlist/${id}`); setWishlisted(data.wishlisted); toast.success(data.wishlisted ? "Added to wishlist" : "Removed from wishlist"); } catch (error) { toast.error(error.response?.data?.message || "Unable to update wishlist"); } };
  if (loading) return <main className="min-h-screen p-16 text-center text-stone-400">Loading product…</main>;
  if (!product) return <main className="min-h-screen p-16 text-center"><p className="text-xl">Product not found.</p><button onClick={() => navigate(-1)} className="mt-4 text-yellow-400">Go back</button></main>;
  return <main className="min-h-screen max-w-6xl mx-auto px-4 py-12"><Link to="/" className="inline-flex items-center gap-2 text-stone-400 hover:text-yellow-400 mb-8"><ArrowLeft size={18}/> Continue shopping</Link><div className="grid lg:grid-cols-2 gap-10"><div className="relative"><img src={product.image} alt={product.name} className="w-full max-h-[620px] object-cover rounded-2xl border border-stone-700"/><button onClick={toggleWishlist} aria-label={wishlisted ? "Remove from wishlist" : "Add to wishlist"} className="absolute right-4 top-4 rounded-full bg-stone-900/90 p-3 text-yellow-400"><Heart fill={wishlisted ? "currentColor" : "none"}/></button></div><section><p className="uppercase tracking-widest text-sm text-yellow-400">{product.category}</p><h1 className="text-4xl font-bold mt-2">{product.name}</h1><div className="mt-3 flex items-center gap-2 text-yellow-400"><Star fill="currentColor" size={18}/><span>{average ? `${average}/5` : "No rating yet"}</span><span className="text-stone-500">({reviews.length} reviews)</span></div><p className="text-3xl font-bold text-yellow-400 mt-6">${price.toFixed(2)}</p><p className="text-stone-300 leading-7 mt-5">{product.description}</p>{product.variants?.length > 0 && <div className="mt-7"><h2 className="font-semibold mb-3">Choose {product.variants[0]?.name?.includes("Size") ? "size" : "variant"}</h2><div className="flex flex-wrap gap-2">{product.variants.map((variant) => <button key={variant._id} onClick={() => setSelectedVariant(variant)} className={`rounded-lg border px-4 py-2 ${selectedVariant?._id === variant._id ? "border-yellow-400 bg-yellow-600/20 text-yellow-300" : "border-stone-600 bg-stone-800"}`}>{variant.name}{variant.price != null ? ` · $${Number(variant.price).toFixed(2)}` : ""}</button>)}</div></div>}<p className={`mt-5 font-medium ${outOfStock ? "text-red-400" : stock <= 5 ? "text-orange-400" : "text-green-400"}`}>{outOfStock ? "Out of stock" : `${stock} available`}</p><button disabled={outOfStock} onClick={add} className="mt-5 w-full rounded-lg bg-yellow-600 py-3 font-semibold hover:bg-yellow-500 disabled:bg-stone-700"><ShoppingCart className="inline mr-2" size={20}/>{outOfStock ? "Out of stock" : "Add to cart"}</button></section></div><section className="mt-16"><h2 className="text-2xl font-bold mb-5">Customer reviews</h2>{reviews.length === 0 ? <p className="text-stone-400">Be the first to review this product.</p> : <div className="grid md:grid-cols-2 gap-4">{reviews.map((review) => <article key={review._id} className="rounded-lg border border-stone-700 bg-stone-800 p-4"><div className="flex justify-between"><strong>{review.user?.name || "Customer"}</strong><span className="text-yellow-400">{"★".repeat(review.rating)}</span></div>{review.title && <h3 className="font-semibold mt-2">{review.title}</h3>}<p className="text-stone-400 mt-2">{review.comment}</p>{review.verifiedPurchase && <span className="text-xs text-green-400">Verified purchase</span>}</article>)}</div>}</section></main>;
}
